docks:
  home_dock:
    type: "nova_carter_dock"
    frame: "map"
    pose: [-0.5, 0.5, 0.0]
  flex_dock1:
    type: "nova_carter_dock"
    frame: "map"
    pose: [-3.0, 1.0, 0.0]
  flex_dock2:
    type: "nova_carter_dock"
    frame: "map"
    pose: [0.0, 5.0, 0.0]