graph:
  nodes:
    - id: "A"
      pose:
        position: {x: 0.0, y: 0.0, z: 0.0}
        orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
    - id: "B"
      pose:
        position: {x: 2.0, y: 0.0, z: 0.0}
        orientation: {x: 1.0, y: 1.0, z: 0.0, w: 1.0}

  edges:
    - from: "A"
      to: "B"
    - from: "B"
      to: "A"
